<#
Install Flutter SDK (stable) on Windows (semi-automated)

Usage:
1. Open PowerShell as Administrator (recommended for PATH changes)
2. Run: `.	ools\install_flutter_windows.ps1` or `.


































































































}  exit 1  Write-Error "Installation failed: $_"} catch {  Write-Log " - Back in terminal: run 'flutter doctor' and fix any issues reported"  Write-Log " - Create an AVD (Device) with AVD Manager"  Write-Log " - In Android Studio: SDK Manager -> Install SDK Platforms and SDK Tools (including 'Android SDK Command-line Tools')"  Write-Log " - Install Android Studio and Android SDK (for emulator & Android tooling): https://developer.android.com/studio"  Write-Log "Installation script finished. Next steps:"  }    Write-Log "flutter not found in current session. Restart your terminal or open a new PowerShell window to use 'flutter'."  } else {    flutter doctor    Write-Log "Running 'flutter doctor' (may ask to accept Android licenses)..."  if ($flutterCmd) {  $flutterCmd = Get-Command flutter -ErrorAction SilentlyContinue  # Run flutter doctor if available  $env:Path = "$env:Path;$flutterBin"  # Update current session PATH so we can run flutter doctor immediately  }    Write-Log "$flutterBin already exists in User PATH."  } else {    Write-Log "Added $flutterBin to User PATH. You may need to restart your shell or sign out/sign in."    [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')    $newPath = if ($currentPath -eq '') { $flutterBin } else { "$currentPath;$flutterBin" }  if ($currentPath -notlike "*${flutterBin}*") {  if (-not $currentPath) { $currentPath = '' }  $currentPath = [Environment]::GetEnvironmentVariable('Path', 'User')  $flutterBin = Join-Path $InstallDir 'bin'  # Add flutter bin to user PATH (if not already present)  }    }      Move-Item -Path $extracted -Destination $InstallDir -Force      if (Test-Path $InstallDir) { Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue }    if (Test-Path $extracted -and $extracted -ne $InstallDir) {    $extracted = Join-Path $parent 'flutter'    # If the extracted folder name is 'flutter' and InstallDir differs, move it    Remove-Item $tmpZip -Force -ErrorAction SilentlyContinue    Expand-Archive -Path $tmpZip -DestinationPath $parent -Force    $parent = Split-Path $InstallDir -Parent    # Extract to parent of InstallDir (e.g., C:\src) so archive's 'flutter' folder is created    Write-Log "Download complete. Extracting..."    Invoke-WebRequest -Uri $FlutterZipUrl -OutFile $tmpZip -UseBasicParsing    $tmpZip = Join-Path $env:TEMP "flutter_sdk.zip"    Write-Log "Git not found. Downloading Flutter ZIP from $FlutterZipUrl"  } else {    }      throw "Git clone failed with exit code $LASTEXITCODE"    if ($LASTEXITCODE -ne 0) {    git clone --depth 1 $GitRepo -b $GitBranch $InstallDir    }      Remove-Item -Recurse -Force -Path $InstallDir -ErrorAction SilentlyContinue      Write-Log "Directory $InstallDir exists. Attempting to remove for fresh clone..."    if (Test-Path $InstallDir) {    Write-Log "Git detected at: $($gitCmd.Source). Cloning Flutter repo (stable branch)..."  if ($gitCmd) {  $gitCmd = Get-Command git -ErrorAction SilentlyContinue  # Prefer git clone if available  }    New-Item -ItemType Directory -Path (Split-Path $InstallDir -Parent) -Force | Out-Null  } else {    Write-Log "Target directory $InstallDir already exists. Skipping creation."   if (Test-Path $InstallDir) {  Write-Log "Starting Flutter installation..."try {}  Write-Host "[flutter-install] $Message"function Write-Log([string]$Message) {)  [string]$FlutterZipUrl = "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.10.5-stable.zip"  [string]$GitBranch = "stable",  [string]$GitRepo = "https://github.com/flutter/flutter.git",  [string]$InstallDir = "C:\src\flutter",param(#>- After the script completes you may need to restart your terminal (or sign out/in) to pick up PATH changes.- If you prefer not to clone, edit `$FlutterZipUrl` to the exact zip release you want.- This script does NOT install Android Studio. Install Android Studio manually for emulators.Notes:- Runs `flutter doctor` (if `flutter` is available in PATH)- Adds `C:\src\flutter\bin` to the current user's PATH (user scope)- If `git` is not available, downloads a stable Flutter ZIP and extracts it- Tries to clone the Flutter `stable` branch from GitHub if `git` is availableWhat the script does:   (or right-click and "Run with PowerShell")ecipes\install_flutter_windows.ps1`